service: wedding-sls
frameworkVersion: "3"
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - v1

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  stage: "v1"
  region: "us-east-1"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:us-east-1:*:table/wedding_jose_mari"

functions:
  listOptions:
    handler: src/application/infra/serverless/functions/listGiftOptions.handle
    events:
      - http:
          path: /gifts
          method: GET
          cors: true
  updateGift:
    handler: src/application/infra/serverless/functions/updateGift.handle
    events:
      - http:
          path: /gifts/quantity
          method: PATCH
          cors: true
  giveGift:
    handler: src/application/infra/serverless/functions/giveGift.handle
    events:
      - http:
          path: /gifts
          method: POST
          cors: true
  login:
    handler: src/application/infra/serverless/functions/login.handle
    events:
      - http:
          path: /guests/login
          method: POST
          cors: true
  updateGuest:
    handler: src/application/infra/serverless/functions/updateGuest.handle
    events:
      - http:
          path: /guests
          method: PUT
          cors: true

resources:
  Resources:
    dynamoDbWedding:
      Type: AWS::DynamoDB::Table
      Properties:
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: wedding_jose_mari
        AttributeDefinitions:
          - AttributeName: kind
            AttributeType: S
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: kind
            KeyType: HASH
          - AttributeName: key
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
